---
title: "git_01"
author: "Math_115jio"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“You are old, Father William,” the young man said,    
“And your hair has become very white;    
And yet you incessantly stand on your head –    
Do you think, at your age, it is right?”    

“In my youth,” Father William replied to his son,    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Having risen from a branch of the Ni River    
during a lull in the Battle of Spotsylvania,    
she settled on the blue upper lip of a dead    
Confederate corporal, weary. As Union troops    
began their fifth assault on Laurel Hill    
she began to molt, her cloudy wings  
clearing with the weather, her spectral body  
brightening and swelling, as if the life  
spilling from the ephemeral creatures around her  
were filling her. Soon, she rose again,  
joining the sudden frenzied cloud of her kind  
congregating then above the creek's  